import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren, ReactNode } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  blogs: ReactNode;
};

export default function RootLayout({
  children,
  blogs,
}: PropsWithChildren<Props>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {blogs}
        {children}
      </body>
    </html>
  );
}
